# Generated by Django 5.2 on 2025-07-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='placeholder',
            field=models.CharField(default='text', max_length=100),
        ),
    ]
