# Generated by Django 5.2 on 2025-07-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='placeholder',
        ),
    ]
